accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='logout'),
]

bonusly2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'', include('thanks.urls')),
]

thanks/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^home/$', views.mainpage, name='mainpage'),
    url(r'^give_points/$', views.give_points, name='give_points'),
]

accounts/models.py
from django.db import models

# Create your models here.

thanks/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator

from django.db import models
from django.db.models.query import QuerySet

class Employee(models.Model):
    user = models.ForeignKey('auth.User')
    points_to_give = models.IntegerField(default=100)
    points_collected = models.IntegerField(default=0)

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name


class Transaction(models.Model):
    giver = models.ForeignKey('thanks.Employee', related_name = "giver")
    receiver = models.ForeignKey('thanks.Employee', related_name = "receiver")
    description = models.TextField(default='')
    points_given = models.IntegerField(default=1, choices=((1,1),(2,2),(3,3)))
    date = models.DateTimeField(default=datetime.now,blank=True)

    def __str__(self):
        return "Transaction #" + str(self.id) + " " + str(self.giver) + " -> " + str(self.receiver)

    def make(self):
        self.date = timezone.now()
        self.save()

thanks/forms.py
from django import forms
from .models import Transaction, Employee

class TransactionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields['receiver'].empty_label = "Select the person"
        self.fields['points_given'].initial = 1  # selecting the first option (1 point) as a default

    class Meta:
        model = Transaction
        fields = ['receiver', 'description', 'points_given']
        labels = {
            'receiver': ('Who do you want to thank?'),
            'description': ('Why do you want to thank?'),
            'points_given': ('How many points do you want to give?'),
        }
        widgets = {
            'description': forms.Textarea(attrs={'placeholder': 'Enter description here', 'rows': 4, 'maxlength': 140 }),
            'points_given': forms.Select(attrs={'placeholder': 'Enter number of points (min. 1 / max. 3)'}),
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

thanks/views.py
from django.shortcuts import render
from .models import Employee, Transaction
from django.contrib.auth import (login as auth_login,  authenticate)
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms	import TransactionForm

def mainpage(request):
	employees = Employee.objects.all().order_by('user')
	collected_points = Employee.objects.get(user_id=request.user.id).points_collected
	transactions = Transaction.objects.all().order_by('-date')
	form = TransactionForm()
	form.fields["receiver"].queryset = Employee.objects.exclude(user_id=request.user.id)

	return render(request, 'thanks/mainpage.html', {'employees': employees, 'transactions': transactions, 'form': form, 'collected_points': collected_points})

def login(request):
    _message = 'Please sign in'
    if request.method == 'POST':
        _username = request.POST['username']
        _password = request.POST['password']
        user = authenticate(username=_username, password=_password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('mainpage'))
            else:
                _message = 'Your account is not activated!'
        else:
            _message = 'Invalid login, please try again.'
    context = {'message': _message}
    return render(request, 'thanks/login.html', context)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

def give_points(request):
	form = TransactionForm(request.POST)

	if form.is_valid():
		transaction = form.save(commit=False)
		loggedUserId = request.user.id
		giv = Employee.objects.get(user_id=loggedUserId)

		transaction.giver = giv
		transaction.save()

		rec2 = Employee.objects.get(id=transaction.receiver_id)
		rec2.points_collected += transaction.points_given
		giv.points_to_give -= transaction.points_given
		rec2.save()
		giv.save()

		form = TransactionForm()
		return mainpage(request)

	args = {'employees': employees,  'transactions': transactions, 'form': form}
	return render(request, 'thanks/mainpage.html', args)

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
<title> Login to Thanks! </title>
{% endblock %}

{% block body %}
<div class="container">

  <form class="form-signin" action="{% url 'accounts:login' %}" method="post" id="login-form">{% csrf_token %}
    <h2 class="form-signin-heading">Welcome to Thanks!</h2>
    <h3 class="form-signin-heading">{{ message }}</h3>
    <label for="id_username" class="sr-only">Email address</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="User Name" required autofocus>
    <label for="id_password" class="sr-only">Password</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
    <div class="checkbox">
      <label>
            <input type="checkbox" value="remember-me">Remember me
          </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
</div>
<!-- /container -->
{% endblock %}

thanks/templates/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- Latest compiled and minified CSS  -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
  <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
   <!-- Latest compiled and minified JavaScript -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  {% block head %}
  <title></title>
  {% endblock %}
</head>

<body>
  {% block body %} {% endblock %}
</body>

</html>

thanks/templates/thanks/mainpage.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}

  <title>Home Page</title>
  <script src="{% static '/js/counter.js' %}"></script>
<!--  {% bootstrap_css %}
  {% bootstrap_javascript %}
-->
  {% endblock %}
</head>

<body>
  {% block body %}
  <div class="container">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" style="padding-top:7px;" href="/home/"><span><img src="{% static '/img/fujitsu.png' %}" style="height:40px; padding-top:0px; padding-right:10px;"></span>Thanks!</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li class="active"><a href="/home/">Home</a></li>
            <li class="dropdown"><a href="#">Options</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><i class="fa fa-user" style="margin-right:5px"></i>{{user.first_name}} {{user.last_name}} <span class="badge" style="margin-bottom:4px;">{{ collected_points }}</span></a></li>
            <li><a href="{% url 'accounts:logout' %}"><i class="fa fas fa-sign-out-alt" style="margin-right:5px"></i>Logout</a></li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
      <!--/.container-fluid -->
    </nav>

    <div class="page-header">
      <h2>Dashboard</h2>
    </div>

    <div class="row">
      <div class="col-md-6">
        <form action="/give_points/" class="form" method="post">
          {% csrf_token %}
          {% bootstrap_field form.receiver %}
          {% bootstrap_field form.description %}
          <div id="chars_counter"></div>
          {% bootstrap_field form.points_given %}
          {% buttons %}
          <button type="submit" type="button" class="btn btn-danger"><i class="far fa-thumbs-up"></i> Send Thanks!</button> {% endbuttons %}
        </form>
      </div>

      <div class="col-md-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Points to give</th>
            <th>Points received</th>
          </tr>
        </thead>
        {% for employee in employees %}
        <tbody>
          <tr>
            <td>{{ employee }}</td>
            <td>{{ employee.points_to_give }}</td>
            <td>{{ employee.points_collected }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </div>

    </div>

    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="page-header">
          <h2>Livefeed</h2>
        </div>
         <div class="livefeed-container">
            {% for transaction in transactions %}
              <div class="transaction-container">
                <div class="transaction-header">
                  <div class="transaction-title">{{ transaction.giver }} gives {{ transaction.receiver }} <span class="badge" style="margin-bottom:4px;">{{ transaction.points_given }}</span> point(s)</div>
                  <div class="transaction-date">{{ transaction.date|date:'d-m-Y H:i' }}</div>
                </div>
                <div class="transaction-description">{{ transaction.description }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
    </div>

  </div>
  {% endblock %}
</body>

</html>